kind: pipeline
type: docker
name: default

steps:
- name: install
  image: node
  commands:
  - npm ci
- name: test
  image: node
  commands:
  - npm test
  depends_on:
  - install
- name: lint
  image: node
  commands:
  - npm run lint
  depends_on:
  - install
- name: build
  image: node
  commands:
  - npm run build
  depends_on:
  - install

---
kind: pipeline
type: docker
name: publish

steps:
- name: publish
  image: plugins/npm
  settings:
    username: CrispyBacon12
    password:
      from_secret: github_password
    email: bob@bob.me
    registry: "https://npm.pkg.github.com/CrispyBacon12"
  commands:
  - npm publish

depends_on:
- default

trigger:
  branch:
  - master
