kind: pipeline
type: docker
name: default

steps:
- name: install
  image: node
  commands:
  - npm ci
- name: test
  image: node
  commands:
  - npm test
  depends_on:
  - install
- name: lint
  image: node
  commands:
  - npm run lint
  depends_on:
  - install
- name: build
  image: node
  commands:
  - npm build
  depends_on:
  - install
